-- MySQL Script generated by MySQL Workbench
-- lun 06 abr 2015 21:43:29 VET
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id` INT NOT NULL COMMENT '		',
  `nombre` VARCHAR(45) NOT NULL,
  `ci` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NULL,
  `afiliacion` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facturas` (
  `id` INT NOT NULL,
  `clientes_id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `total` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_facturas_clientes1_idx` (`clientes_id` ASC),
  CONSTRAINT `fk_facturas_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `mydb`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `id` INT NOT NULL COMMENT '		',
  `nombre` VARCHAR(45) NOT NULL COMMENT '	',
  `precio` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `facturas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productos_facturas_idx` (`facturas_id` ASC),
  CONSTRAINT `fk_productos_facturas`
    FOREIGN KEY (`facturas_id`)
    REFERENCES `mydb`.`facturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
